name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build and push Docker Image 1
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/secrets:latest -f Dockerfile1 .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/secrets:latest

      - name: Build and push Docker Image 2
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/service:latest -f Dockerfile2 .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/service:latest
